FROM golang:1.22.2

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY gen ./gen
COPY proto ./proto

RUN go build -o lambda-processor ./cmd/lambda

CMD [ "./lambda-processor" ]